/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.Timer;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.table.DefaultTableModel;
import procesos.GestorLocks;

/**
 *
 * @author ikers
 */
public class VentanaPrincipal extends javax.swing.JFrame {
private logica_sistema.SimuladorSD disco;
private logica_sistema.AdministradorArchivos admin;
private procesos.GestorLocks gestorLocks;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        // Creamos un disco de 400 bloques (20x20 cuadritos)
this.disco = new logica_sistema.SimuladorSD(400); 
this.admin = new logica_sistema.AdministradorArchivos(this.disco);
this.gestorLocks = new procesos.GestorLocks();
jLabel1.setText("Posición del Cabezal: " + disco.getPosicionCabezal());


((gui.PanelDisco) this.jPanel1).setSimulador(this.disco);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new gui.PanelDisco();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaSolicitudes = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtNuevaPosicion = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaProcesos = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        btnTerminarProceso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTree1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Bloques", "Inicio", "Color"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("Crear Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modo Administrador", "Modo Usuario" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIFO (First-In, First-Out)", "SSTF (Shortest Seek Time First)", "SCAN", "C-SCAN" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Posición del Cabezal: 0");

        jScrollPane3.setViewportView(listaSolicitudes);

        jButton3.setText("Simular Lectura");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Ir a");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtNuevaPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevaPosicionActionPerformed(evt);
            }
        });

        tablaProcesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Proceso", "Archivo en Uso", "Estado"
            }
        ));
        jScrollPane4.setViewportView(tablaProcesos);

        jButton5.setText("Abrir Proceso");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnTerminarProceso.setText("Terminar Proceso");
        btnTerminarProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarProcesoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton2)
                                            .addComponent(jButton1))
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jButton3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(8, 8, 8)
                                        .addComponent(txtNuevaPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4))))
                            .addComponent(jButton5)
                            .addComponent(btnTerminarProceso))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtNuevaPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4)))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTerminarProceso)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try {
    // Pedimos los datos al usuario con ventanitas emergentes
    String nombre = javax.swing.JOptionPane.showInputDialog(this, "Nombre del archivo:");
    if (nombre == null || nombre.trim().isEmpty()) return; // Si cancela o deja vacío, salimos

    String tamanoStr = javax.swing.JOptionPane.showInputDialog(this, "Tamaño en bloques:");
    if (tamanoStr == null) return;

    int tamano = Integer.parseInt(tamanoStr); // Validamos que sea un número 
    if (tamano <= 0) throw new NumberFormatException();

    String dueno = "Admin"; // Por ahora estático

    // Generamos un color aleatorio para diferenciar los archivos [cite: 33]
    java.awt.Color colorAleatorio = new java.awt.Color((int)(Math.random() * 0x1000000));

    // Llamamos al cerebro para crear el archivo
    boolean exito = admin.crearArchivo(nombre, tamano, dueno, colorAleatorio);

    if (exito) {
        jPanel1.repaint();
        if (exito) {
    jPanel1.repaint(); // Actualiza el disco
    actualizarTabla(); // <--- AGREGA ESTA LÍNEA
    actualizarArbol(); // <--- AGREGA ESTA LÍNEA
    javax.swing.JOptionPane.showMessageDialog(this, "¡Archivo creado!");
}
        javax.swing.JOptionPane.showMessageDialog(this, "¡Archivo '" + nombre + "' creado con éxito!");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: No hay espacio suficiente en el disco.");
    }
} catch (NumberFormatException e) {
    // Si el usuario mete letras en el tamaño, el programa no explota [cite: 187, 188]
    javax.swing.JOptionPane.showMessageDialog(this, "Error: El tamaño debe ser un número entero mayor a cero.");
}       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
// 1. Obtener la opción seleccionada
String modo = jComboBox1.getSelectedItem().toString();

// 2. Si es Modo Usuario, desactivamos los botones de escritura (Crear y Eliminar)
if (modo.equals("Modo Usuario")) {
    jButton1.setEnabled(false); // Botón Crear
    jButton2.setEnabled(false); // Botón Eliminar
    javax.swing.JOptionPane.showMessageDialog(this, "Modo Lectura activado. No se permiten modificaciones.");
} else {
    // 3. Si es Modo Administrador, reactivamos todo
    jButton1.setEnabled(true);
    jButton2.setEnabled(true);
}        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// 1. Verificar si hay una fila seleccionada
    int filaSeleccionada = jTable1.getSelectedRow();
    if (filaSeleccionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona un archivo de la tabla para eliminar.");
        return;
    }

    // 2. Obtener el nombre de forma segura
    Object valorCelda = jTable1.getValueAt(filaSeleccionada, 0);
    if (valorCelda == null) return;
    String archivoAEliminar = valorCelda.toString();

    // 3. VALIDACIÓN DE SEGURIDAD (LOCKS)
    for (int i = 0; i < tablaProcesos.getRowCount(); i++) {
        Object archivoEnProceso = tablaProcesos.getValueAt(i, 1);
        if (archivoEnProceso != null && archivoEnProceso.toString().equals(archivoAEliminar)) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡ERROR! No se puede eliminar un archivo que está siendo usado por un proceso activo.");
            return; 
        }
    }

    // 4. Si pasó la validación, confirmar y borrar
    int confirmar = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Estás seguro de eliminar " + archivoAEliminar + "?", 
            "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
        // 5. Llamar al cerebro para liberar bloques y borrar de la lista
        boolean exito = admin.eliminarArchivo(archivoAEliminar);

        if (exito) {
            // 6. Actualizar toda la interfaz
            jPanel1.repaint();      // Los bloques vuelven a blanco
            actualizarTabla();      // Desaparece de la tabla
            actualizarArbol();      // Desaparece del JTree
            javax.swing.JOptionPane.showMessageDialog(this, "Archivo eliminado y bloques liberados.");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al intentar eliminar el archivo.");
        }
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int fila = jTable1.getSelectedRow();
if (fila == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un archivo de la tabla");
    return;
}

// 1. Obtener bloques del archivo seleccionado
String nombre = jTable1.getValueAt(fila, 0).toString();
estructuras.ListaEnlazada<Integer> bloquesOriginales = null;

for (int i = 0; i < admin.getCarpetaActual().getArchivos().size(); i++) {
    if (admin.getCarpetaActual().getArchivos().get(i).getNombre().equals(nombre)) {
        bloquesOriginales = admin.getCarpetaActual().getArchivos().get(i).getBloquesAsignados();
        break;
    }
}

// 2. Crear el planificador de Alma con la posición actual del cabezal
planificacion.PlanificadorDisco planificador = new planificacion.PlanificadorDisco(disco.getPosicionCabezal());

// 3. Aplicar el algoritmo seleccionado
String algoritmo = jComboBox2.getSelectedItem().toString();
estructuras.ListaEnlazada<Integer> bloquesOrdenados;

if (algoritmo.contains("SSTF")) {
    bloquesOrdenados = planificador.planificarSSTF(bloquesOriginales);
} else if (algoritmo.contains("SCAN")) {
    // SCAN necesita saber si sube o baja, le pondremos 'true' por defecto
    bloquesOrdenados = planificador.planificarSCAN(bloquesOriginales, true);
} else if (algoritmo.contains("C-SCAN")) {
    bloquesOrdenados = planificador.planificarCSCAN(bloquesOriginales);
} else {
    // FIFO: El orden de llegada
    bloquesOrdenados = planificador.planificarFIFO(bloquesOriginales);
}
// --- CÓDIGO PARA LLENAR LA LISTA DE SOLICITUDES ---
// 1. Creamos un modelo para la lista
javax.swing.DefaultListModel<String> modeloLista = new javax.swing.DefaultListModel<>();

// 2. Recorremos los bloques que ya ordenó el algoritmo (SSTF, FIFO, etc.)
for (int i = 0; i < bloquesOrdenados.size(); i++) {
    modeloLista.addElement("Bloque: " + bloquesOrdenados.get(i));
}

// 3. Le pasamos el modelo a tu JList
listaSolicitudes.setModel(modeloLista);
// --------------------------------------------------

// Ahora sí, lanzamos la animación que ya tenías
ejecutarAnimacionCabezal(bloquesOrdenados);
// 4. Lanzar la animación con la lista que ordenó el planificador
ejecutarAnimacionCabezal(bloquesOrdenados);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try {
    // 1. Leemos el número que escribiste en el cuadrito (ej. 50)
    int nuevaPos = Integer.parseInt(txtNuevaPosicion.getText());
    
    // 2. Validamos que sea un bloque real (del 0 al 399)
    if (nuevaPos >= 0 && nuevaPos < 400) {
        
        // 3. Actualizamos la LÓGICA (el objeto disco)
        disco.setPosicionCabezal(nuevaPos);
        
        // 4. Actualizamos la VISTA (la etiqueta que ve el usuario)
        // Cambia 'jLabel3' por el nombre real de tu etiqueta de posición
        jButton4.setText("Posición del Cabezal: " + nuevaPos);
        
        javax.swing.JOptionPane.showMessageDialog(this, "Cabezal posicionado en el bloque " + nuevaPos);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: El disco solo tiene bloques del 0 al 399.");
    }
} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingresa un número válido.");
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtNuevaPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevaPosicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevaPosicionActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
int fila = jTable1.getSelectedRow(); // Verifica que sea jTable1 o jTable2 según tu diseño
if (fila == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un archivo para que el proceso lo use.");
    return;
}

String nombreArchivo = jTable1.getValueAt(fila, 0).toString();

// 1. Usamos el objeto gestorLocks para pedir permiso de escritura
if (gestorLocks.solicitarEscritura(nombreArchivo)) {
    
    // 2. Si se pudo bloquear, lo agregamos a la tabla de procesos
    DefaultTableModel modelo = (DefaultTableModel) tablaProcesos.getModel();
    modelo.addRow(new Object[]{"P-" + (modelo.getRowCount() + 1), nombreArchivo, "ESCRITURA (LOCK)"});
    
    javax.swing.JOptionPane.showMessageDialog(this, "Proceso iniciado. Archivo '" + nombreArchivo + "' bloqueado con éxito.");
} else {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: El archivo ya está siendo usado por otro proceso.");
}     // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnTerminarProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarProcesoActionPerformed
int fila = tablaProcesos.getSelectedRow();
if (fila == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un proceso de la tabla para terminarlo.");
    return;
}

// 1. Obtener el nombre del archivo que tiene el lock
String nombreArchivo = tablaProcesos.getValueAt(fila, 1).toString();

// 2. Usar el gestor de Alma para liberar el Lock de Escritura
gestorLocks.liberarEscritura(nombreArchivo);

// 3. Quitar la fila de la tabla de procesos
DefaultTableModel modelo = (DefaultTableModel) tablaProcesos.getModel();
modelo.removeRow(fila);

javax.swing.JOptionPane.showMessageDialog(this, "Proceso terminado. El archivo '" + nombreArchivo + "' ahora está libre.");        // TODO add your handling code here:
    }//GEN-LAST:event_btnTerminarProcesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTerminarProceso;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTree jTree1;
    private javax.swing.JList<String> listaSolicitudes;
    private javax.swing.JTable tablaProcesos;
    private javax.swing.JTextField txtNuevaPosicion;
    // End of variables declaration//GEN-END:variables
private void actualizarTabla() {
    // Obtenemos el modelo de la tabla que dibujaste en el diseño
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    
    // Limpiamos la tabla para no duplicar datos
    modelo.setRowCount(0);

    // Obtenemos la lista de archivos de la carpeta actual usando el Administrador
    estructuras.ListaEnlazada<sistema_archivos.Archivo> listaArchivos = admin.getCarpetaActual().getArchivos();

    for (int i = 0; i < listaArchivos.size(); i++) {
        sistema_archivos.Archivo arc = listaArchivos.get(i);
        
        // Creamos la fila con: Nombre, Bloques, Inicio (primer bloque), Color
        Object[] fila = {
            arc.getNombre(), 
            arc.getTamañoBloques(), 
            arc.getBloquesAsignados().get(0), // Dirección del primer bloque [cite: 65]
            "Color Asignado" // Aquí podrías poner el nombre del color o un indicador visual [cite: 66]
        };
        modelo.addRow(fila);
    }
}
    private void actualizarArbol() {
    // Nodo raíz visual
    javax.swing.tree.DefaultMutableTreeNode rootVisual = new javax.swing.tree.DefaultMutableTreeNode(admin.getRaiz().getNombre());
    
    // Obtenemos los archivos de la carpeta actual
    estructuras.ListaEnlazada<sistema_archivos.Archivo> archivos = admin.getCarpetaActual().getArchivos();
    
    for (int i = 0; i < archivos.size(); i++) {
        // Agregamos cada archivo como un nodo hijo [cite: 28]
        rootVisual.add(new javax.swing.tree.DefaultMutableTreeNode(archivos.get(i).getNombre()));
    }

    // Aplicamos el nuevo modelo al JTree que arrastraste
    jTree1.setModel(new javax.swing.tree.DefaultTreeModel(rootVisual));
}
   private void moverCabezal(int destino) {
    disco.setPosicionCabezal(destino);
    // Cambia jLabel3 por el nombre que tenga tu etiqueta de "Posición del Cabezal"
    jLabel1.setText("Posición del Cabezal: " + destino);
}
   private void ejecutarAnimacionCabezal(estructuras.ListaEnlazada<Integer> bloques) {
    // Usamos un índice para saber por qué bloque vamos
    final int[] indice = {0};

    Timer timer = new Timer(500, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if (indice[0] < bloques.size()) {
                int bloqueDestino = bloques.get(indice[0]);
                moverCabezal(bloqueDestino); // El método que ya creamos
                
                // Opcional: imprimir en consola para debug
                System.out.println("Visitando bloque: " + bloqueDestino);
                
                indice[0]++;
            } else {
                ((Timer)e.getSource()).stop(); // Detener cuando termine la lista
                javax.swing.JOptionPane.showMessageDialog(null, "Simulación finalizada.");
            }
        }
    });
    timer.start();
}
}

