/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author ikers
 */
public class VentanaPrincipal extends javax.swing.JFrame {
private logica_sistema.SimuladorSD disco;
private logica_sistema.AdministradorArchivos admin;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        // Creamos un disco de 400 bloques (20x20 cuadritos)
this.disco = new logica_sistema.SimuladorSD(400); 
this.admin = new logica_sistema.AdministradorArchivos(this.disco);


((gui.PanelDisco) this.jPanel1).setSimulador(this.disco);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new gui.PanelDisco();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTree1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Bloques", "Inicio", "Color"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("Crear Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modo Administrador", "Modo Usuario" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIFO (First-In, First-Out)", "SSTF (Shortest Seek Time First)", "SCAN", "C-SCAN" }));

        jLabel1.setText("Posición del Cabezal: 0");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        jLabel2.setText("Algoritmo de Planificación");

        jButton3.setText("Simular Lectura");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1)))
                        .addGap(338, 338, 338))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2))
                                .addComponent(jComboBox1)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(5, 5, 5)))
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try {
    // Pedimos los datos al usuario con ventanitas emergentes
    String nombre = javax.swing.JOptionPane.showInputDialog(this, "Nombre del archivo:");
    if (nombre == null || nombre.trim().isEmpty()) return; // Si cancela o deja vacío, salimos

    String tamanoStr = javax.swing.JOptionPane.showInputDialog(this, "Tamaño en bloques:");
    if (tamanoStr == null) return;

    int tamano = Integer.parseInt(tamanoStr); // Validamos que sea un número 
    if (tamano <= 0) throw new NumberFormatException();

    String dueno = "Admin"; // Por ahora estático

    // Generamos un color aleatorio para diferenciar los archivos [cite: 33]
    java.awt.Color colorAleatorio = new java.awt.Color((int)(Math.random() * 0x1000000));

    // Llamamos al cerebro para crear el archivo
    boolean exito = admin.crearArchivo(nombre, tamano, dueno, colorAleatorio);

    if (exito) {
        jPanel1.repaint();
        if (exito) {
    jPanel1.repaint(); // Actualiza el disco
    actualizarTabla(); // <--- AGREGA ESTA LÍNEA
    actualizarArbol(); // <--- AGREGA ESTA LÍNEA
    javax.swing.JOptionPane.showMessageDialog(this, "¡Archivo creado!");
}
        javax.swing.JOptionPane.showMessageDialog(this, "¡Archivo '" + nombre + "' creado con éxito!");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: No hay espacio suficiente en el disco.");
    }
} catch (NumberFormatException e) {
    // Si el usuario mete letras en el tamaño, el programa no explota [cite: 187, 188]
    javax.swing.JOptionPane.showMessageDialog(this, "Error: El tamaño debe ser un número entero mayor a cero.");
}       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
// 1. Obtener la opción seleccionada
String modo = jComboBox1.getSelectedItem().toString();

// 2. Si es Modo Usuario, desactivamos los botones de escritura (Crear y Eliminar)
if (modo.equals("Modo Usuario")) {
    jButton1.setEnabled(false); // Botón Crear
    jButton2.setEnabled(false); // Botón Eliminar
    javax.swing.JOptionPane.showMessageDialog(this, "Modo Lectura activado. No se permiten modificaciones.");
} else {
    // 3. Si es Modo Administrador, reactivamos todo
    jButton1.setEnabled(true);
    jButton2.setEnabled(true);
}        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// 1. Obtener la fila seleccionada en la tabla
int filaSeleccionada = jTable1.getSelectedRow();

if (filaSeleccionada == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona un archivo de la tabla para eliminar.");
    return;
}

// 2. Obtener el nombre del archivo de la primera columna (columna 0)
String nombreEliminar = jTable1.getValueAt(filaSeleccionada, 0).toString();

// 3. Confirmar eliminación
int confirmar = javax.swing.JOptionPane.showConfirmDialog(this, 
    "¿Estás seguro de eliminar '" + nombreEliminar + "'?", "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);

if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
    // 4. Llamar al cerebro para liberar bloques y borrar de la lista
    boolean exito = admin.eliminarArchivo(nombreEliminar);

    if (exito) {
        // 5. Actualizar toda la interfaz
        jPanel1.repaint();   // Los bloques vuelven a blanco [cite: 35]
        actualizarTabla();   // Desaparece de la tabla [cite: 67]
        actualizarArbol();   // Desaparece del JTree [cite: 24]
        javax.swing.JOptionPane.showMessageDialog(this, "Archivo eliminado y bloques liberados.");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al intentar eliminar el archivo.");
    }
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
private void actualizarTabla() {
    // Obtenemos el modelo de la tabla que dibujaste en el diseño
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    
    // Limpiamos la tabla para no duplicar datos
    modelo.setRowCount(0);

    // Obtenemos la lista de archivos de la carpeta actual usando el Administrador
    estructuras.ListaEnlazada<sistema_archivos.Archivo> listaArchivos = admin.getCarpetaActual().getArchivos();

    for (int i = 0; i < listaArchivos.size(); i++) {
        sistema_archivos.Archivo arc = listaArchivos.get(i);
        
        // Creamos la fila con: Nombre, Bloques, Inicio (primer bloque), Color
        Object[] fila = {
            arc.getNombre(), 
            arc.getTamañoBloques(), 
            arc.getBloquesAsignados().get(0), // Dirección del primer bloque [cite: 65]
            "Color Asignado" // Aquí podrías poner el nombre del color o un indicador visual [cite: 66]
        };
        modelo.addRow(fila);
    }
}
    private void actualizarArbol() {
    // Nodo raíz visual
    javax.swing.tree.DefaultMutableTreeNode rootVisual = new javax.swing.tree.DefaultMutableTreeNode(admin.getRaiz().getNombre());
    
    // Obtenemos los archivos de la carpeta actual
    estructuras.ListaEnlazada<sistema_archivos.Archivo> archivos = admin.getCarpetaActual().getArchivos();
    
    for (int i = 0; i < archivos.size(); i++) {
        // Agregamos cada archivo como un nodo hijo [cite: 28]
        rootVisual.add(new javax.swing.tree.DefaultMutableTreeNode(archivos.get(i).getNombre()));
    }

    // Aplicamos el nuevo modelo al JTree que arrastraste
    jTree1.setModel(new javax.swing.tree.DefaultTreeModel(rootVisual));
}
}

